"""ReportLab implementation of PDFGeneratorPort."""
import logging
from io import BytesIO
from typing import Optional

from app.domain.report import MedicalReport
from app.ports.pdf_generator import PDFGeneratorPort

logger = logging.getLogger(__name__)


class ReportLabPDFGenerator:
    """
    Generate professional medical PDFs using ReportLab.
    No external dependencies beyond reportlab (pure Python).
    """
    
    def __init__(
        self,
        default_disclaimer: str = "",
        logo_path: Optional[str] = None,
    ):
        self.default_disclaimer = default_disclaimer or (
            "This simulation is generated by AI for illustrative purposes only. "
            "Results may vary. Consult with a qualified hair transplant surgeon "
            "for professional medical advice."
        )
        self.logo_path = logo_path
    
    def generate_medical_report(
        self,
        report: MedicalReport,
        include_disclaimer: bool = True,
        watermark: str = "",
    ) -> bytes:
        """
        Generate medical-grade PDF report.
        """
        try:
            from reportlab.lib import colors
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.platypus import (
                Image as RLImage,
                Paragraph,
                SimpleDocTemplate,
                Spacer,
                Table,
                TableStyle,
            )
        except ImportError:
            raise ImportError(
                "reportlab not installed. Run: pip install reportlab"
            )
        
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2*cm,
            topMargin=2*cm,
            bottomMargin=2*cm,
        )
        
        styles = getSampleStyleSheet()
        story = []
        
        # Header
        header_style = ParagraphStyle(
            'CustomHeader',
            parent=styles['Heading1'],
            fontSize=18,
            textColor=colors.HexColor('#1a1a2e'),
            spaceAfter=12,
        )
        
        clinic_name = report.clinic_name or "CapillarAI Medical Report"
        story.append(Paragraph(clinic_name, header_style))
        story.append(Spacer(1, 0.5*cm))
        
        # Metadata table
        meta_data = [
            ["Report ID:", report.report_id],
            ["Date:", report.created_at.strftime("%Y-%m-%d %H:%M UTC")],
            ["Patient Reference:", report.patient_reference or "Anonymous"],
        ]
        
        if report.scalp_analysis:
            meta_data.append([
                "Severity Level:",
                report.scalp_analysis.severity.value.title()
            ])
        
        meta_table = Table(meta_data, colWidths=[4*cm, 10*cm])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 1*cm))
        
        # Images comparison
        story.append(Paragraph("Simulation Results", styles['Heading2']))
        story.append(Spacer(1, 0.3*cm))
        
        # Side-by-side images
        img_width = 7*cm
        img_height = 7*cm
        
        # Original image
        orig_img = RLImage(BytesIO(report.original_image), width=img_width, height=img_height)
        
        # Simulation image
        sim_img = RLImage(BytesIO(report.simulation_image), width=img_width, height=img_height)
        
        img_table = Table(
            [[orig_img, sim_img], ["Before", "After (Simulation)"]],
            colWidths=[8*cm, 8*cm],
        )
        img_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 1), (-1, 1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 1), (-1, 1), 10),
            ('TOPPADDING', (0, 1), (-1, 1), 6),
        ]))
        story.append(img_table)
        story.append(Spacer(1, 1*cm))
        
        # Analysis section
        if report.donor_analysis:
            story.append(Paragraph("Donor Area Analysis", styles['Heading2']))
            
            donor_data = [
                ["Metric", "Value"],
                ["Density Score", f"{report.donor_analysis.density_score:.1f}/10"],
                ["Estimated Grafts Available", str(report.donor_analysis.estimated_grafts)],
                ["Donor Coverage Area", f"{report.donor_analysis.coverage_area_cm2:.1f} cm²"],
                ["Recommendation", report.donor_analysis.recommendation.value.replace("_", " ").title()],
                ["Confidence", f"{report.donor_analysis.confidence:.0%}"],
            ]
            
            if report.donor_analysis.reasoning:
                donor_data.append(["Analysis", report.donor_analysis.reasoning])
            
            donor_table = Table(donor_data, colWidths=[6*cm, 8*cm])
            donor_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a1a2e')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('FONTNAME', (0, 1), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(donor_table)
            story.append(Spacer(1, 0.5*cm))
            
            # Grafts needed calculation
            total_needed = report.total_estimated_grafts()
            if total_needed:
                story.append(Paragraph(
                    f"<b>Estimated grafts required for coverage:</b> {total_needed:,}",
                    styles['Normal']
                ))
            story.append(Spacer(1, 1*cm))
        
        # Simulation parameters
        if report.simulation_params:
            story.append(Paragraph("Simulation Parameters", styles['Heading2']))
            params_data = [
                ["Profile", report.simulation_params.profile_name],
                ["Inference Steps", str(report.simulation_params.num_inference_steps)],
                ["Inpaint Strength", f"{report.simulation_params.inpaint_strength:.2f}"],
                ["Guidance Scale", f"{report.simulation_params.guidance_scale:.2f}"],
            ]
            if report.simulation_params.seed:
                params_data.append(["Seed", str(report.simulation_params.seed)])
            
            params_table = Table(params_data, colWidths=[6*cm, 8*cm])
            params_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            story.append(params_table)
            story.append(Spacer(1, 1*cm))
        
        # Disclaimer
        if include_disclaimer:
            story.append(Spacer(1, 1*cm))
            disclaimer = report.disclaimer_text or self.default_disclaimer
            disclaimer_para = Paragraph(
                f"<i>{disclaimer}</i>",
                ParagraphStyle(
                    'Disclaimer',
                    parent=styles['Normal'],
                    fontSize=8,
                    textColor=colors.grey,
                    alignment=1,  # Center
                )
            )
            story.append(disclaimer_para)
        
        # Watermark (if requested)
        if watermark:
            # Watermark would be drawn on canvas in real implementation
            pass
        
        doc.build(story)
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
    
    def generate_batch_summary(
        self,
        reports: list[MedicalReport],
        clinic_name: str,
    ) -> bytes:
        """Generate summary PDF for batch processing."""
        # Simplified implementation
        return self.generate_medical_report(
            reports[0] if reports else MedicalReport(),
            include_disclaimer=True,
        )
